import { prompts, submitForm } from "./prompts";
import { openRetentionEditor, type Bucket } from "./retention";
import { showCredential } from "./credential";
import { openQuantityEditor, unitKindFor } from "./quantity";

/**
 * Settings page interactions.
 *
 * Editing is typed from the schema: a bool gets a select, a duration and an int
 * get text fields with the shape named in the placeholder. The server validates
 * regardless, so this only shortens the feedback loop.
 */
document.addEventListener("submit", async (event) => {
  const form = event.target;
  if (!(form instanceof HTMLFormElement) || !form.matches("[data-confirm-s3key]")) return;
  event.preventDefault();
  const confirmed = await prompts.confirm({
    title: "Delete access key",
    badge: form.dataset.confirmS3key,
    message: "The key stops working immediately and stays deleted across restarts, even if it was originally seeded from configuration.",
    confirmText: "Delete key",
    variant: "danger",
  });
  if (confirmed) form.submit();
});

document.addEventListener("click", async (event) => {
  const target = event.target;
  if (!(target instanceof Element)) return;

  const edit = target.closest<HTMLElement>("[data-setting-edit]");
  if (edit) {
    const path = edit.dataset.settingEdit ?? "";
    const type = edit.dataset.settingType ?? "string";
    const current = edit.dataset.settingValue ?? "";

    const quantity = unitKindFor(type, edit.dataset.settingUnit);
    if (quantity) {
      const value = await openQuantityEditor({ path, kind: quantity, current, hint: hintFor(type) });
      if (value !== null) submitForm("/settings/apply", { path, type, value });
      return;
    }

    // Retention gets a real editor: it is a list of rules, not a string.
    if (type === "retentionBuckets") {
      let buckets: Bucket[] = [];
      try {
        buckets = JSON.parse(edit.dataset.settingJson ?? "[]") as Bucket[];
      } catch {
        buckets = [];
      }
      const value = await openRetentionEditor(buckets);
      if (value !== null) submitForm("/settings/apply", { path, type, value });
      return;
    }

    const values = await prompts.form({
      title: "Change setting",
      badge: path,
      message: hintFor(type),
      confirmText: "Apply",
      fields: [
        type === "bool"
          ? { name: "value", label: "Value", value: current === "true" ? "true" : "false", options: [{ value: "true", label: "true" }, { value: "false", label: "false" }] }
          : { name: "value", label: "Value", value: current === "-" ? "" : current, placeholder: placeholderFor(type), required: true },
      ],
    });
    if (values) submitForm("/settings/apply", { path, type, value: values.value ?? "" });
    return;
  }

  const rotate = target.closest<HTMLElement>("[data-s3key-rotate]");
  if (rotate) {
    const accessKey = rotate.dataset.s3keyRotate ?? "";
    const confirmed = await prompts.confirm({
      title: "Rotate secret",
      badge: accessKey,
      message: "Issues a new secret and invalidates the current one immediately. Anything still using the old secret stops working.",
      confirmText: "Rotate",
    });
    if (!confirmed) return;
    const res = await fetch(`/api/s3keys/${encodeURIComponent(accessKey)}/rotate`, { method: "POST", credentials: "same-origin" });
    const body = await res.json();
    if (!res.ok) {
      await prompts.confirm({ title: "Could not rotate key", message: body.error ?? "Unknown error", confirmText: "Close" });
      return;
    }
    showCredential({ title: "Secret rotated", accessKey: body.accessKey, secretKey: body.secretKey, note: "The previous secret stopped working immediately." });
    return;
  }

  const create = target.closest<HTMLElement>("[data-s3key-create]");
  if (create) {
    // Offer the mounts that actually exist: a grant naming a bucket the server
    // does not have is rejected on save, which is a slow way to learn it.
    const mounts = (create.dataset.mounts ?? "").split(",").filter(Boolean);
    const values = await prompts.form({
      title: "Create access key",
      message: "The access key and secret are generated by the server and the secret is shown once. Choose which buckets this key may reach.",
      confirmText: "Create key",
      fields: [
        {
          name: "buckets",
          label: "Buckets",
          value: "*",
          options: [{ value: "*", label: "All mounts" }, ...mounts.map((mount) => ({ value: mount, label: mount }))],
        },
        { name: "requestsPerSecond", label: "Requests per second", placeholder: "leave empty for no limit" },
      ],
    });
    if (!values) return;

    const res = await fetch("/api/s3keys/create", {
      method: "POST",
      headers: { "content-type": "application/json" },
      credentials: "same-origin",
      body: JSON.stringify({ buckets: [values.buckets ?? "*"], requestsPerSecond: values.requestsPerSecond ?? "" }),
    });
    const body = await res.json();
    if (!res.ok) {
      await prompts.confirm({ title: "Could not create key", message: body.error ?? "Unknown error", confirmText: "Close" });
      return;
    }
    showCredential({
      title: "Access key created",
      accessKey: body.accessKey,
      secretKey: body.secretKey,
      note: `Buckets: ${(body.buckets ?? []).join(", ")}`,
    });
  }
});

function hintFor(type: string): string {
  if (type === "retentionBuckets") {
    return "One rule per line: keep_for=<duration>,max_count=<n>. max_count=-1 keeps everything in that window. Rules are windows measured back from now, so 1h then 24h then 720h forms a decay schedule.";
  }
  if (type === "duration") return "A Go duration such as 30s, 5m or 24h.";
  if (type === "stringList") return "Comma separated. Leave empty for none.";
  if (type === "int") return "A whole number. Byte limits are in bytes.";
  return "The server validates the value before applying it.";
}

function placeholderFor(type: string): string {
  if (type === "duration") return "5m";
  if (type === "stringList") return "one, two";
  if (type === "int") return "1048576";
  return "";
}
