package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	apiv1 "github.com/valentinkolb/filegate/api/v1"
)

// newConfigSchemaCmd prints the config key catalog.
//
// Fifty-five keys split across two scopes is more than an operator can hold in
// their head, and the difference between the two -- whether an edit needs a
// restart -- is the question they actually have. The markdown format writes the
// published reference page, so the docs cannot drift from the spec table the
// server itself validates against.
func newConfigSchemaCmd() *cobra.Command {
	var format string
	cmd := &cobra.Command{
		Use:   "schema",
		Short: "Print every config key with its type, scope and default",
		Long: "Print every config key with its type, scope and default.\n\n" +
			"Manifest-owned runtime keys apply immediately. Manifest-owned static keys are\n" +
			"stored as desired state and need a restart. Bootstrap and resource-owned keys\n" +
			"cannot be changed by a manifest.",
		RunE: func(cmd *cobra.Command, _ []string) error {
			schema := configSchema()
			switch strings.ToLower(strings.TrimSpace(format)) {
			case "table", "":
				return writeSchemaTable(cmd.OutOrStdout(), schema)
			case "json":
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetEscapeHTML(false)
				enc.SetIndent("", "  ")
				return enc.Encode(schema)
			case "markdown":
				return writeSchemaMarkdown(cmd.OutOrStdout(), schema)
			default:
				return fmt.Errorf("--format must be table, json or markdown")
			}
		},
	}
	cmd.Flags().StringVar(&format, "format", "table", "output format: table, json or markdown")
	return cmd
}

func writeSchemaTable(w io.Writer, schema []apiv1.ConfigKeySchema) error {
	width := 0
	for _, key := range schema {
		if len(key.Path) > width {
			width = len(key.Path)
		}
	}
	for _, key := range schema {
		def := schemaDefault(key)
		if def == "" {
			def = "-"
		}
		if _, err := fmt.Fprintf(w, "%-*s  %-7s  %-9s  %-12s  %s\n", width, key.Path, key.Scope, key.ManagedBy, kindLabel(key.Type), def); err != nil {
			return err
		}
	}
	return nil
}

// schemaGroups splits the keys by their leading path segment, keeping the spec
// table's order within each group and ordering the groups by first appearance.
func schemaGroups(schema []apiv1.ConfigKeySchema) ([]string, map[string][]apiv1.ConfigKeySchema) {
	order := make([]string, 0, 12)
	groups := make(map[string][]apiv1.ConfigKeySchema)
	for _, key := range schema {
		group, _, _ := strings.Cut(key.Path, ".")
		if _, seen := groups[group]; !seen {
			order = append(order, group)
		}
		groups[group] = append(groups[group], key)
	}
	return order, groups
}

func writeSchemaMarkdown(w io.Writer, schema []apiv1.ConfigKeySchema) error {
	var b strings.Builder

	b.WriteString("---\n")
	b.WriteString("title: Config reference\n")
	b.WriteString("navTitle: Config\n")
	b.WriteString("section: Reference\n")
	b.WriteString("order: 200\n")
	b.WriteString("description: Complete Filegate configuration key reference, including which keys change without a restart.\n")
	b.WriteString("tags: [reference, config]\n")
	b.WriteString("---\n\n")

	b.WriteString("<!-- Generated by `make docs-config`. Edit cli/config_flags.go, not this file. -->\n\n")
	b.WriteString("# Config reference\n\n")
	b.WriteString("This reference catalogs every Filegate configuration key, when a change activates, and which surface owns it.\n\n")
	b.WriteString("Environment variables use `FILEGATE_` plus the uppercase config path with `_` separators. Example: `server.listen` becomes `FILEGATE_SERVER_LISTEN`.\n\n")

	static, runtime := 0, 0
	owners := map[string]int{}
	secrets := make([]string, 0, 4)
	for _, key := range schema {
		if key.Scope == "static" {
			static++
		} else {
			runtime++
		}
		owners[key.ManagedBy]++
		if key.Secret {
			secrets = append(secrets, key.Path)
		}
	}

	b.WriteString("## Activation and ownership\n\n")
	b.WriteString("A manifest is a complete desired-state replacement. Runtime keys activate when `fg config apply` succeeds. Static keys are stored immediately but remain pending until restart.\n\n")
	b.WriteString("| Activation | Keys | Effect |\n|---|---:|---|\n")
	fmt.Fprintf(&b, "| `static` | %d | Desired state is stored; the running process changes after restart. |\n", static)
	fmt.Fprintf(&b, "| `runtime` | %d | The running snapshot changes immediately. |\n\n", runtime)
	b.WriteString("| Managed by | Keys | Meaning |\n|---|---:|---|\n")
	fmt.Fprintf(&b, "| `manifest` | %d | Accepted by the complete manifest in `fg config plan/apply`. |\n", owners[apiv1.ConfigManagedByManifest])
	fmt.Fprintf(&b, "| `bootstrap` | %d | Read from file, environment, or startup flags; excluded from manifests. |\n", owners[apiv1.ConfigManagedByBootstrap])
	fmt.Fprintf(&b, "| `resource` | %d | Managed through its dedicated resource API, not configuration apply. |\n\n", owners[apiv1.ConfigManagedByResource])

	if len(secrets) > 0 {
		sorted := append([]string(nil), secrets...)
		sort.Strings(sorted)
		b.WriteString("Secret keys are excluded from manifests, never returned by the config API, and redacted by `fg config show`; they report only whether a value is configured. ")
		b.WriteString("They are " + joinCode(sorted) + ".\n\n")
	}

	order, groups := schemaGroups(schema)
	for _, group := range order {
		fmt.Fprintf(&b, "## %s\n\n", groupTitle(group))
		b.WriteString("| Key | Type | Activation | Managed by | Default | Meaning |\n|---|---|---|---|---|---|\n")
		for _, key := range groups[group] {
			def := schemaDefault(key)
			if def == "" {
				def = "-"
			} else {
				def = "`" + def + "`"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s |\n", key.Path, kindLabel(key.Type), key.Scope, key.ManagedBy, def, schemaMeaning(key))
		}
		b.WriteString("\n")
	}

	_, err := io.WriteString(w, b.String())
	return err
}

func groupTitle(group string) string {
	switch group {
	case "s3":
		return "S3"
	case "cors":
		return "CORS"
	default:
		return strings.ToUpper(group[:1]) + group[1:]
	}
}

func joinCode(values []string) string {
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = "`" + value + "`"
	}
	if len(quoted) == 1 {
		return quoted[0]
	}
	return strings.Join(quoted[:len(quoted)-1], ", ") + " and " + quoted[len(quoted)-1]
}

func kindLabel(kind string) string {
	switch kind {
	case "stringList":
		return "string list"
	case "s3Keys":
		return "S3 key list"
	case "retentionBuckets":
		return "retention buckets"
	default:
		return kind
	}
}

// schemaMeaning is the usage text plus, for static keys, the reason a restart
// is required -- the one thing an operator staring at a rejected edit wants.
func schemaMeaning(key apiv1.ConfigKeySchema) string {
	meaning := strings.TrimSpace(key.Usage)
	if meaning != "" {
		meaning = strings.ToUpper(meaning[:1]) + meaning[1:]
		if !strings.HasSuffix(meaning, ".") {
			meaning += "."
		}
	}
	if key.Unit != "" {
		meaning += " Measured in " + key.Unit + "."
	}
	if key.Reason != "" {
		meaning += " Needs a restart: " + key.Reason + "."
	}
	if key.Secret {
		meaning += " Secret; never returned by the API."
	}
	return strings.TrimSpace(strings.ReplaceAll(meaning, "|", "\\|"))
}

// schemaDefault renders a default compactly. Empty strings, empty lists and
// zero-length durations all render as blank so the table shows "-" rather than
// a value an operator might mistake for a real setting.
func schemaDefault(key apiv1.ConfigKeySchema) string {
	if key.Secret || key.Default == nil {
		return ""
	}
	switch value := key.Default.(type) {
	case string:
		return value
	case bool:
		return fmt.Sprintf("%t", value)
	case []string:
		if len(value) == 0 {
			return ""
		}
		return strings.Join(value, ", ")
	case []any:
		if len(value) == 0 {
			return ""
		}
	}
	encoded, err := json.Marshal(key.Default)
	if err != nil {
		return ""
	}
	text := string(encoded)
	if text == "null" || text == `""` || text == "[]" || text == "{}" || text == "0" {
		return ""
	}
	return text
}
