package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const generatedConfigReference = "../docs-site/docs/en/reference/config.md"

// The published config reference is generated from the spec table. Without this
// guard the two drift the moment someone adds a key, and a reference that is
// quietly one key short is worse than no reference: an operator concludes the
// setting does not exist.
func TestConfigReferenceIsCurrent(t *testing.T) {
	var generated bytes.Buffer
	if err := writeSchemaMarkdown(&generated, configSchema()); err != nil {
		t.Fatalf("render markdown: %v", err)
	}

	committed, err := os.ReadFile(filepath.Clean(generatedConfigReference))
	if err != nil {
		t.Fatalf("read committed reference: %v", err)
	}

	if generated.String() != string(committed) {
		t.Fatalf("%s is stale; run `make docs-config`", generatedConfigReference)
	}
}

func TestConfigSchemaMarkdownCoversEveryKey(t *testing.T) {
	var out bytes.Buffer
	if err := writeSchemaMarkdown(&out, configSchema()); err != nil {
		t.Fatalf("render markdown: %v", err)
	}
	rendered := out.String()

	for _, spec := range allConfigFlagSpecs() {
		if !strings.Contains(rendered, "`"+spec.Path+"`") {
			t.Errorf("config reference is missing %s", spec.Path)
		}
	}
}

// A secret's value must not reach the page, and the page is the one config
// artifact that gets pasted into issues and chat.
func TestConfigSchemaMarkdownOmitsSecretDefaults(t *testing.T) {
	for _, key := range configSchema() {
		if !key.Secret {
			continue
		}
		if key.Default != nil {
			t.Errorf("%s is secret but carries a default in the schema", key.Path)
		}
		if got := schemaDefault(key); got != "" {
			t.Errorf("%s is secret but renders default %q", key.Path, got)
		}
	}
}
